name: Build MainsailOS - Raspberry Pi OS buster
on:
  push:
    branches:
      - '**'
    #paths:
    #- 'src/**'
    #- 'emulation/**'
    tags-ignore:
      - '**'
  pull_request:
    types: [ opened, edited ]
    #paths:
    #- 'src/**'
    #- 'emulation/**'

jobs:
  raspiosbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt update; sudo apt install --yes coreutils p7zip-full qemu-user-static zip

      - name: Checkout CustomPiOS
        uses: actions/checkout@v2
        with:
          repository: 'guysoft/CustomPiOS'
          path: CustomPiOS

      - name: Checkout MainsailOS Project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
          submodules: true

      - name: Download Raspberry Pi OS Source Image
        run: aria2c -d repository/src/image/ --seed-time=0 https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf_latest.torrent

      - name: Comparing Checksums
        run: |
          cd repository/src/image
          curl -JL https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf_latest.sha256 | awk '{print $1"  "$2}' | sha256sum -c

      - name: Update CustomPiOS Paths
        run: cd repository/src && ../../CustomPiOS/src/update-custompios-paths

      - name: Build Image
        run: sudo modprobe loop && cd repository/src && sudo bash -x ./build_dist

      - name: Copy output image
        run: cp ${{ github.workspace }}/repository/src/workspace/*-raspios-*-lite.img mainsailos-raspios-lite-latest.img

      - name: Compress the image
        run: zip mainsailos-raspios-lite-latest.zip mainsailos-raspios-lite-latest.img

      - uses: actions/upload-artifact@v1
        with:
          name: mainsailos-raspios-lite-latest.zip
          path: mainsailos-raspios-lite-latest.zip