name: "Linter: Commit Lint"
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  commitlinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
