name: Build and Release MainsailOS - Raspberry Pi OS buster
on:
  release:
    types: [ published ]

env:
  DOWNLOAD_URL_CHECKSUM: "https://downloads.raspberrypi.org/raspios_lite_armhf_latest.sha256"
  DOWNLOAD_URL_IMAGE: "https://downloads.raspberrypi.org/raspios_lite_armhf_latest.torrent"
  FILENAME_CHECKSUM: "raspios_lite_armhf_latest.sha256"

jobs:
  raspiosbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt update; sudo apt install --yes coreutils p7zip-full qemu-user-static zip

      - name: Checkout CustomPiOS
        uses: actions/checkout@v2
        with:
          repository: "guysoft/CustomPiOS"
          path: CustomPiOS

      - name: Checkout MainsailOS Project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
          submodules: true

      - name: Raspberry Pi OS Checksum
        id: raspios-checksum
        run: |
          cd repository/src/image
          wget -O $FILENAME_CHECKSUM $DOWNLOAD_URL_CHECKSUM
          FILE_CONTENT=$(head -n 1 $FILENAME_CHECKSUM)
          CHECKSUM=$(echo $FILE_CONTENT | cut -d' ' -f1)
          echo "::set-output name=CHECKSUM::$CHECKSUM"

      - name: Cache Raspberry Pi OS Source Image
        id: cache-source-image
        uses: actions/cache@v3
        with:
          path: repository/src/image/*.img.xz
          key: ${{ runner.os }}-${{ steps.raspios-checksum.outputs.CHECKSUM }}

      - name: Download Raspberry Pi OS Source Image
        if: steps.cache-source-image.outputs.cache-hit != 'true'
        run: aria2c -d repository/src/image --seed-time=0 $DOWNLOAD_URL_IMAGE

      - name: Comparing Checksums
        run: |
          cd repository/src/image
          cat $FILENAME_CHECKSUM | awk '{print $1"  "$2}' | sha256sum -c

      - name: Update CustomPiOS Paths
        run: cd repository/src && ../../CustomPiOS/src/update-custompios-paths

      - name: Build Image
        run: sudo modprobe loop && cd repository/src && sudo bash -x ./build_dist

      - name: Copy output image
        run: cp ${{ github.workspace }}/repository/src/workspace/*-raspios-*-lite.img MainsailOS-buster-lite-${{ github.event.release.tag_name }}.img

      - name: Compress the image
        run: zip MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip MainsailOS-buster-lite-${{ github.event.release.tag_name }}.img

      - name: Generate sha256 Checksum
        run: sha256sum MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip > MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip.sha256

      - uses: actions/upload-artifact@v2
        with:
          name: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip
          path: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip

      - name: Upload MainsailOS (Raspios buster based) Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip
          asset_name: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload MainsailOS sha256 Checksum Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip.sha256
          asset_name: MainsailOS-buster-lite-${{ github.event.release.tag_name }}.zip.sha256
          asset_content_type: text/plain
